#!/bin/sh

TOP=$(dirname $0)/..

# Prepare for header filter
for i in $@; do
    BASE=$(basename $i)
    if [ "$BASE" == "$i" ]; then
        echo "ERROR $i is a local file."
        continue
    fi

    touch $BASE
done

# Bring in and filter files
for i in $@; do
    BASE=$(basename $i)
    if [ "$BASE" == "$i" ]; then
        echo "ERROR $i is a local file."
        continue
    fi

    cp "$i" "$BASE"
    cleanupFiles -u -h --clean-commas "$BASE"
    if [ "$BASE" != "$(basename "$BASE" .cpp)" ]; then
        cleanupFiles -f $(dirname $0)/CPP_FILTER --fix-ending-namepace "$BASE"
    fi
    rm "$BASE"*~
done
